spring.application.name=router-simulator
server.port=8081
spring.threads.virtual.enabled=true
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
router.simulator.topic=router-metrics
router.simulator.device-count=10
router.simulator.publish-interval-ms=5000
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always